const letras = [
    "A", "a", "B", "b", "C", "c", "D", "d", "E", "e", "F", "f", "G", "g", "H", "h", "I",
    "i", "J", "j", "K", "k", "L", "l", "M", "m", "N", "n", "O", "o", "P", "p", "Q", "q",
    "R", "r", "S", "s", "T", "t", "U", "u", "V", "v", "W", "w", "X", "x", "Y", "y", "Z", "z",
    "Ç", "ç"
];

const numeros = [
    "0", "1", "2", "3", "4",
    "5", "6", "7", "8", "9"
];

const letras_E_numeros = [
    "A", "a", "B", "b", "C", "c", "D", "d", "E", "e", "F", "f", "G", "g", "H", "h", "I",
    "i", "J", "j", "K", "k", "L", "l", "M", "m", "N", "n", "O", "o", "P", "p", "Q", "q",
    "R", "r", "S", "s", "T", "t", "U", "u", "V", "v", "W", "w", "X", "x", "Y", "y", "Z",
    "z", "Ç", "ç", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9"
];

let beforeWord = [
  // BR
  "Achei essa palavra:", "Como aplicar a palavra", "Em qual contexto uso", "Gíria ou formal:", 
  "De onde surgiu", "Pesquisando por", "Exemplos práticos de", "A gramática de", "Dúvida sobre", 
  "Alguém sabe o que é", "A origem secreta de", "Por que usar", "Não entendi o termo", 
  "Como escrever", "Contexto histórico de", "Explicação rápida para", "O conceito de", "Defina", 
  "O que a galera entende por", "Termo do dia:", "Buscando:", "Como conjugar", "Qual a etimologia de", 
  "A tradução literal de", "O uso correto de", "Como não errar ao falar", "Pode me explicar", 
  "Qual a vibe de", "O que significa na gíria", "Em inglês seria o equivalente a", 
  "No dia a dia, como uso", "Anotando aqui:", "Memorizar a palavra", "O que o dicionário diz sobre", 
  "Qual a moral de", "Testando a palavra", "Duvido você saber o que é", "Lendo sobre", 
  "Curiosidade sobre", "Fale mais sobre", "O sinônimo perfeito para", "Antônimo exato de", 
  "Citação com a palavra", "Frase de exemplo com", "Como pronunciar corretamente", "A pronúncia exata de",
  "Como usar essa palavra em uma redação", "Essa palavra tem duplo sentido", 
  "Quais são as expressões idiomáticas com", "Essa palavra ainda é usada ou está em desuso", 
  "Qual é a diferença entre", "Em qual preposição eu uso a palavra", "Como usar isso em uma frase", 
  "Existe alguma gíria equivalente a", "Qual é a sílaba tônica de", "Essa palavra é um falso cognato",
  "Qual é o significado de", "Queria saber mais sobre", "Alguém me explica o que é",
  "Hoje eu aprendi o termo", "Sempre tive dúvida sobre", "Como eu traduzo",
  "O que diabos significa", "Nunca ouvi falar na palavra", "De onde tiraram a expressão",
  "Estou tentando entender", "Me deparei com a palavra", "Como aplicar no dia a dia:",
  "Isso aqui é um palavrão?", "Qual o antônimo para", "Sinônimos interessantes para",
  "Tem alguma gíria para", "Como falar formalmente", "Achei essa expressão num livro:",
  "Estudando hoje:", "O que o Google diz sobre", "Qual é a classe gramatical de",
  "É um substantivo ou adjetivo?", "Como fica o plural de", "Essa palavra tem acento?",
  "Regras de uso para", "Qual é o radical da palavra", "Sufixo e prefixo de",
  "Dá pra usar no sentido figurado?", "Sentido literal de", "Como encaixar no texto:",
  "O professor falou hoje:", "Vi num filme a palavra", "Apareceu numa série:",
  "Como se pronuncia isso:", "Qual a origem histórica de", "Quem inventou a palavra",
  "Isso é do latim ou do grego?", "Palavra muito usada no Brasil:", "Em Portugal significa a mesma coisa?",
  "Isso é regionalismo?", "Expressão típica de", "Será que isso existe no dicionário?",
  "O corretor ortográfico marcou:", "Palavra chique para impressionar:", "Vocabulário avançado:",
  "Enriquecendo o vocabulário com", "Substitua a palavra", "Outra forma de dizer",
  "Como ser mais educado ao dizer", "Palavra bonita do dia:", "Que palavra estranha:",
  "A pronúncia me confunde em", "Escrevi certo a palavra", "Qual é a raiz de",
  "Análise sintática de", "Como é a regência de", "Verbo transitivo ou intransitivo?",
  "Como eu conjugo no passado:", "No futuro, como fica", "Modo subjuntivo de",
  "Tem alguma exceção para", "Essa palavra é um neologismo?", "Caiu na prova de concurso:",
  "Achei no Enem a palavra", "Questão de português sobre", "Dúvida cruel:",
  "Como explicar para um estrangeiro o que é", "Tem equivalente em inglês para",
  "Gosto muito do som da palavra", "Minha palavra favorita é", "Odeio a sonoridade de",
  "Palavra difícil de pronunciar:", "Trava-língua com a palavra", "Rima perfeita para",
  "O que rima com", "Poema curto usando", "Letra de música com",
  "Vi no Twitter a gíria", "Os jovens estão usando muito:", "Viralizou no TikTok o termo",
  "Trending topic de hoje:", "O que significa a hashtag", "Meme do dia envolvendo",
  "Isso é coisa de gente velha?", "Expressão de boomer:", "Linguagem da geração Z:",
  "Como os gamers usam", "Termo técnico da área de TI:", "No jargão corporativo, o que é",
  "Como colocar no currículo:", "Palavra boa para usar no trabalho:", "E-mail formal usando",
  "Ficou estranho eu dizer", "Cometi uma gafe ao falar", "Fui corrigido ao usar",
  "Não sei se escreve junto ou separado:", "Tem hífen em", "Usa crase antes de",
  "É com S ou com Z:", "Termina com M ou N:", "Com X ou CH:",
  "Com G ou J:", "Letra muda em", "Qual é o diminutivo de",
  "Qual é o aumentativo de", "Noção básica sobre", "Para que serve a palavra",
  "Dando um Google rápido em", "Pesquisa avançada sobre", "O Chat GPT me sugeriu a palavra",
  "A inteligência artificial gerou:", "Estou montando uma frase com", "Preciso de inspiração para usar",
  "Criando um texto com", "Reescreva a frase usando", "Redação nota mil usando",
  "Dica de português:", "Macete para lembrar de", "Associação mental para a palavra",
  "Flashcard de hoje:", "Revisão de vocabulário:", "Teste de proficiência:",
  "Qual o nível dessa palavra (A1-C2)?", "Palavra comum em textos acadêmicos:", "Linguagem jurídica:",
  "Isso é jargão médico?", "Vocabulário de economia:", "Termo da filosofia:",
  "Na sociologia, o que significa", "Conceito psicológico de", "Explique como se eu tivesse 5 anos:",
  "Resumo rápido de", "Definição longa de", "O que a Wikipédia fala sobre",
  "Bate-papo sobre", "Trocando uma ideia sobre", "Reflexão do dia com a palavra",
  "Isso me faz pensar em", "Associo essa palavra a", "Qual a primeira coisa que vem à mente com",
  "Palavra que define meu humor hoje:", "Estado de espírito:", "Isso descreve perfeitamente",
  "Quando ouço isso, imagino", "Uma imagem que representa", "Qual cor combina com a palavra",
  "Tem alguma música sobre", "Livro que tem no título", "Nome de filme com",
  "Pessoa famosa que sempre fala", "Bordão envolvendo", "Slogan com a palavra",
  "Frase motivacional com", "Provérbio usando", "Ditado popular com",
  "Sabedoria popular sobre", "Mito ou verdade sobre a palavra", "A polêmica em torno de",
  "Por que todo mundo está falando de", "O hype da palavra", "Essa palavra foi cancelada?",
  "Apropriação cultural do termo", "Significado original de", "Como o sentido mudou com o tempo:",
  "Evolução da palavra", "Palavra do ano passado:", "Apostas para a palavra do ano:",
  "Para fechar com chave de ouro, use",

  // EN
  "I found this word:", "How to apply the word", "In what context do I use", "Slang or formal:", 
  "Where did it come from", "Searching for", "Practical examples of", "The grammar of", "Question about", 
  "Does anyone know what is", "The secret origin of", "Why use", "I didn't understand the term", 
  "How to spell", "Historical context of", "Quick explanation for", "The concept of", "Define", 
  "What do people mean by", "Word of the day:", "Looking up:", "How to conjugate", 
  "What is the etymology of", "The literal translation of", "The correct use of", "How not to misuse", 
  "Can you explain", "What is the vibe of", "What does it mean in slang", "In daily life, how do I use", 
  "Taking notes on:", "Memorize the word", "What the dictionary says about", "What's the point of", 
  "Testing the word", "I bet you don't know what is", "Reading about", "Curiosity about", 
  "Tell me more about", "The perfect synonym for", "Exact antonym of", "Quote with the word", 
  "Example sentence with", "How to correctly pronounce", "The exact pronunciation of",
  "Is this commonly used by native speakers", "What are some common collocations for", 
  "Are there any idioms related to", "How formal or casual is this expression", 
  "Is this word used more in British or American English", "How to use this in a sentence", 
  "Is there a slang term for", "Which syllable is stressed in", "What preposition goes with", 
  "Is this a false friend",
  "What exactly does this mean", "I need a definition for", "Can someone explain",
  "Today I learned the word", "I've always wondered about", "How do I translate",
  "What on earth does this mean", "Never heard of the word", "Where did they get the expression",
  "Trying to wrap my head around", "Stumbled upon the word", "How to apply in daily life:",
  "Is this a swear word?", "What's the antonym for", "Interesting synonyms for",
  "Is there a slang term for", "How to say this formally", "Found this expression in a book:",
  "Studying today:", "What does Google say about", "What part of speech is",
  "Is it a noun or an adjective?", "What's the plural form of", "Does this word have an accent?",
  "Rules of usage for", "What's the root of the word", "Suffix and prefix for",
  "Can I use this figuratively?", "The literal meaning of", "How to fit this into a text:",
  "The teacher mentioned today:", "Saw the word in a movie", "Popped up in a TV show:",
  "How do you pronounce this:", "What is the historical origin of", "Who coined the word",
  "Is this from Latin or Greek?", "A very common word in the US:", "Does it mean the same in the UK?",
  "Is this a regionalism?", "Typical expression from", "Is this even in the dictionary?",
  "The spellchecker flagged:", "Fancy word to impress:", "Advanced vocabulary:",
  "Expanding my vocabulary with", "Replace the word", "Another way to say",
  "Polite way to say", "Beautiful word of the day:", "What a weird word:",
  "The pronunciation of this confuses me", "Did I spell this right", "What is the stem of",
  "Syntactic analysis of", "What preposition goes with", "Transitive or intransitive verb?",
  "How do I conjugate this in the past:", "In the future tense, it becomes", "Subjunctive mood of",
  "Are there any exceptions for", "Is this word a neologism?", "Popped up on my exam:",
  "Found this on the SAT:", "Grammar question about", "Crucial doubt:",
  "How to explain this to a non-native speaker:", "Is there a Portuguese equivalent for",
  "I love the sound of this word", "My favorite English word is", "I hate how this sounds:",
  "Hard word to pronounce:", "Tongue twister with the word", "Perfect rhyme for",
  "What rhymes with", "Short poem using", "Song lyrics featuring",
  "Saw this slang on Twitter", "Young people are using this a lot:", "Went viral on TikTok:",
  "Today's trending topic:", "What does the hashtag mean", "Meme of the day featuring",
  "Is this an old person thing?", "Boomer expression:", "Gen Z language:",
  "How gamers use the term", "Tech jargon:", "In corporate jargon, what is",
  "How to put this on a resume:", "Good word for the workplace:", "Formal email using",
  "Did it sound weird when I said", "I made a faux pas saying", "I was corrected for using",
  "Is it one word or two?", "Is there a hyphen in", "Do I use 'a' or 'an' before",
  "Is it spelled with a C or an S:", "Ends with a T or an E:", "Double letters in",
  "Silent letter in", "What is the diminutive of", "Is this an uncountable noun?",
  "Basic notion of", "What is the purpose of the word", "Urban Dictionary definition for",
  "A quick Google search for", "Deep dive into", "ChatGPT suggested the word",
  "The AI generated:", "I'm building a sentence with", "Need inspiration to use",
  "Writing an essay with", "Rewrite the sentence using", "Top score IELTS essay using",
  "English tip:", "Trick to remember", "Mental association for the word",
  "Today's flashcard:", "Vocabulary review:", "TOEFL Proficiency test:",
  "What CEFR level is this word (A1-C2)?", "Common word in academic papers:", "Legal jargon:",
  "Is this medical jargon?", "Economics vocabulary:", "Philosophy term:",
  "In sociology, what does this mean", "Psychological concept of", "Explain like I'm 5:",
  "Quick summary of", "Long definition of", "What Wikipedia says about",
  "Chatting about", "Bouncing ideas about", "Thought of the day with the word",
  "This makes me think of", "I associate this word with", "First thing that comes to mind with",
  "Word that defines my mood today:", "State of mind:", "This perfectly describes",
  "When I hear this, I imagine", "An image that represents", "What color matches the word",
  "Is there a song about", "Book with the title", "Movie name with",
  "Famous person who always says", "Catchphrase involving", "Slogan with the word",
  "Motivational quote with", "Proverb using", "Popular saying with",
  "Folk wisdom about", "Myth or truth about the word", "The controversy surrounding",
  "Why is everyone talking about", "The hype around the word", "Has this word been canceled?",
  "Cultural appropriation of the term", "Original meaning of", "How the meaning changed over time:",
  "Evolution of the word", "Word of the year:", "Bets for the word of the year:",
  "To top it all off, use", "Is this a Britishism?", "American equivalent of", 
  "British equivalent of", "Aussie slang for", "Irish slang for",
  // ES
  "Encontré esta palabra:", "Cómo aplicar la palabra", "En qué contexto uso", "Jerga o formal:", 
  "De dónde surgió", "Buscando", "Ejemplos prácticos de", "La gramática de", "Duda sobre", 
  "Alguien sabe qué es", "El origen secreto de", "Por qué usar", "No entendí el término", 
  "Cómo escribir", "Contexto histórico de", "Explicación rápida para", "El concepto de", "Define", 
  "Qué entiende la gente por", "Palabra del día:", "Consultando:", "Cómo conjugar", 
  "Cuál es la etimología de", "La traducción literal de", "El uso correcto de", 
  "Cómo no equivocarse al decir", "Me puedes explicar", "Qué onda con", "Qué significa en la jerga", 
  "En el día a día, cómo uso", "Tomando nota de:", "Memorizar la palabra", 
  "Qué dice el diccionario sobre", "Cuál es el punto de", "Probando la palabra", 
  "Apuesto a que no sabes qué es", "Leyendo sobre", "Curiosidad sobre", "Cuéntame más sobre", 
  "El sinónimo perfecto para", "Antónimo exacto de", "Cita con la palabra", "Frase de ejemplo con", 
  "Cómo pronunciar correctamente", "La pronunciación exacta de",
  "Se usa más en España o en Latinoamérica", "Qué tono tiene esta palabra", 
  "Frases hechas con la palabra", "Es una palabra de uso cotidiano", 
  "Palabras de la misma familia léxica que", "Cómo usar esto en una oración", 
  "Hay alguna jerga para", "Cuál es la sílaba tónica de", "Qué preposición acompaña a", 
  "Es un falso amigo",
  "Cuál es el significado de", "Quería saber más sobre", "Alguien me explica qué es",
  "Hoy aprendí el término", "Siempre tuve la duda sobre", "Cómo traduzco",
  "Qué diablos significa", "Nunca escuché la palabra", "De dónde sacaron la expresión",
  "Intentando entender", "Me topé con la palabra", "Cómo aplicarlo en el día a día:",
  "¿Es esto una grosería?", "Cuál es el antónimo de", "Sinónimos interesantes para",
  "Hay alguna jerga para", "Cómo decirlo formalmente", "Encontré esta expresión en un libro:",
  "Estudiando hoy:", "Qué dice Google sobre", "Cuál es la categoría gramatical de",
  "¿Es un sustantivo o un adjetivo?", "Cómo es el plural de", "¿Esta palabra lleva tilde?",
  "Reglas de uso para", "Cuál es la raíz de la palabra", "Sufijo y prefijo de",
  "¿Se puede usar en sentido figurado?", "El sentido literal de", "Cómo encajar esto en un texto:",
  "El profesor mencionó hoy:", "Vi en una película la palabra", "Apareció en una serie:",
  "Cómo se pronuncia esto:", "Cuál es el origen histórico de", "Quién inventó la palabra",
  "¿Viene del latín o del griego?", "Palabra muy usada en México:", "¿En España significa lo mismo?",
  "¿Es un regionalismo?", "Expresión típica de", "¿Estará esto en el diccionario de la RAE?",
  "El corrector ortográfico marcó:", "Palabra elegante para impresionar:", "Vocabulario avanzado:",
  "Ampliando mi vocabulario con", "Reemplaza la palabra", "Otra forma de decir",
  "Manera educada de decir", "Palabra hermosa del día:", "Qué palabra tan extraña:",
  "La pronunciación me confunde en", "Escribí bien la palabra", "Cuál es la raíz de",
  "Análisis sintáctico de", "Cómo es la regencia de", "¿Verbo transitivo o intransitivo?",
  "Cómo conjugo esto en pasado:", "En futuro, cómo queda", "Modo subjuntivo de",
  "¿Hay alguna excepción para", "¿Es esta palabra un neologismo?", "Salió en el examen:",
  "Pregunta de gramática sobre", "Duda cruel:",
  "Cómo explicar a un extranjero qué es", "Tiene equivalente en inglés para",
  "Me encanta cómo suena esta palabra", "Mi palabra favorita es", "Odio cómo suena",
  "Palabra difícil de pronunciar:", "Trabalenguas con la palabra", "Rima perfecta para",
  "Qué rima con", "Poema corto usando", "Letra de canción con",
  "Vi en Twitter la jerga", "Los jóvenes usan mucho:", "Se hizo viral en TikTok el término",
  "Tema en tendencia de hoy:", "Qué significa el hashtag", "Meme del día con",
  "¿Es esto cosa de viejos?", "Expresión de boomer:", "Lenguaje de la generación Z:",
  "Cómo lo usan los gamers", "Término técnico de TI:", "En la jerga corporativa, qué es",
  "Cómo poner en el currículum:", "Buena palabra para usar en el trabajo:", "Correo formal usando",
  "Sonó raro cuando dije", "Cometí un error al usar", "Me corrigieron por decir",
  "No sé si se escribe junto o separado:", "Lleva guion", "Va con C, S o Z:",
  "Termina con M o N:", "Con B o V:", "Con G o J:", "Con Y o LL:", 
  "Letra muda en", "Cuál es el diminutivo de",
  "Cuál es el aumentativo de", "Noción básica sobre", "Para qué sirve la palabra",
  "Buscando rápido en Google", "Búsqueda avanzada sobre", "Chat GPT me sugirió la palabra",
  "La inteligencia artificial generó:", "Estoy armando una frase con", "Necesito inspiración para usar",
  "Escribiendo un texto con", "Reescribe la oración usando", "Redacción perfecta usando",
  "Consejo de español:", "Truco para recordar", "Asociación mental para la palabra",
  "Tarjeta de memoria de hoy:", "Repaso de vocabulario:", "Prueba de nivel DELE:",
  "¿Qué nivel es esta palabra (A1-C2)?", "Palabra común en textos académicos:", "Lenguaje jurídico:",
  "¿Es esto jerga médica?", "Vocabulario de economía:", "Término de filosofía:",
  "En sociología, qué significa", "Concepto psicológico de", "Explícalo como si tuviera 5 años:",
  "Resumen rápido de", "Definición larga de", "Qué dice Wikipedia sobre",
  "Charlando sobre", "Intercambiando ideas sobre", "Reflexión del día con la palabra",
  "Esto me hace pensar en", "Asocio esta palabra a", "La primera cosa que me viene a la mente con",
  "Palabra que define mi humor hoy:", "Estado de ánimo:", "Esto describe perfectamente",
  "Cuando escucho esto, imagino", "Una imagen que representa", "Qué color combina con la palabra",
  "Hay alguna canción sobre", "Libro que tiene en el título", "Nombre de película con",
  "Persona famosa que siempre dice", "Frase célebre involucrando", "Eslogan con la palabra",
  "Frase motivacional con", "Proverbio usando", "Dicho popular con",
  "Sabiduría popular sobre", "Mito o verdad sobre la palabra", "La polémica en torno a",
  "Por qué todos hablan de", "El furor de la palabra", "¿Fue cancelada esta palabra?",
  "Apropiación cultural del término", "Significado original de", "Cómo cambió el sentido con el tiempo:",
  "Evolución de la palabra", "Palabra del año pasado:", "Apuestas para la palabra del año:",
  "Para cerrar con broche de oro, usa", "Palabra muy usada en Argentina:", "Modismo colombiano:",
  "Chilenismo:", "Palabra típica de Perú:", "Jerga de Puerto Rico:", "Español castizo de Madrid:",

  // FR
  "J'ai trouvé ce mot:", "Comment appliquer le mot", "Dans quel contexte utiliser", "Argot ou formel:", 
  "D'où vient", "En recherchant", "Exemples pratiques de", "La grammaire de", "Question sur", 
  "Quelqu'un sait ce qu'est", "L'origine secrète de", "Pourquoi utiliser", "Je n'ai pas compris le terme", 
  "Comment écrire", "Contexte historique de", "Explication rapide pour", "Le concept de", "Définir", 
  "Que comprennent les gens par", "Mot du jour:", "En cherchant:", "Comment conjuguer", 
  "Quelle est l'étymologie de", "La traduction littérale de", "L'utilisation correcte de", 
  "Comment ne pas se tromper en disant", "Pouvez-vous expliquer", "C'est quoi l'ambiance de", 
  "Que signifie en argot", "Au quotidien, comment utiliser", "Prendre des notes sur:", 
  "Mémoriser le mot", "Que dit le dictionnaire sur", "Quel est le but de", "Tester le mot", 
  "Je parie que vous ne savez pas ce qu'est", "Lire sur", "Curiosité sur", "Dites-m'en plus sur", 
  "Le synonyme parfait pour", "Antonyme exact de", "Citation avec le mot", "Phrase d'exemple avec", 
  "Comment prononcer correctement", "La prononciation exacte de",
  "Est-ce qu'on utilise ce mot plutôt à l'oral ou à l'écrit", "Quel est le registre de langue de ce mot", 
  "Y a-t-il des faux amis pour ce mot en français", "Est-ce un mot ringard ou à la mode", 
  "Peut-on l'utiliser au sens figuré", "Comment utiliser cela dans une phrase", 
  "Y a-t-il un argot pour", "Quelle est la syllabe tonique de", "Quelle préposition utiliser avec", 
  "Est-ce que c'est un faux ami",
  "Quel est le sens de", "Je voulais en savoir plus sur", "Quelqu'un peut m'expliquer ce qu'est",
  "Aujourd'hui j'ai appris le terme", "J'ai toujours eu un doute sur", "Comment je traduis",
  "Que diable signifie", "Je n'ai jamais entendu le mot", "D'où sortent-ils l'expression",
  "J'essaie de comprendre", "Je suis tombé sur le mot", "Comment l'appliquer au quotidien :",
  "Est-ce un gros mot ?", "Quel est l'antonyme de", "Des synonymes intéressants pour",
  "Y a-t-il un mot d'argot pour", "Comment dire ça de façon formelle", "J'ai trouvé cette expression dans un livre :",
  "En étudiant aujourd'hui :", "Que dit Google à propos de", "Quelle est la nature grammaticale de",
  "Est-ce un nom ou un adjectif ?", "Quel est le pluriel de", "Est-ce qu'il y a un accent circonflexe sur",
  "Règles d'utilisation pour", "Quelle est la racine du mot", "Suffixe et préfixe de",
  "Peut-on l'utiliser au sens figuré ?", "Le sens littéral de", "Comment intégrer ça dans un texte :",
  "Le professeur a mentionné aujourd'hui :", "J'ai vu ce mot dans un film", "C'est apparu dans une série :",
  "Comment ça se prononce :", "Quelle est l'origine historique de", "Qui a inventé le mot",
  "Ça vient du latin ou du grec ?", "Mot très utilisé en France :", "Au Québec, ça veut dire la même chose ?",
  "Est-ce un régionalisme ?", "Expression typique de", "Est-ce que c'est dans le dictionnaire Larousse ?",
  "Le correcteur orthographique a souligné :", "Mot élégant pour impressionner :", "Vocabulaire avancé :",
  "Enrichir mon vocabulaire avec", "Remplacez le mot", "Une autre façon de dire",
  "Façon polie de dire", "Beau mot du jour :", "Quel mot bizarre :",
  "La prononciation me pose problème dans", "Ai-je bien orthographié le mot", "Quel est le radical de",
  "Analyse syntaxique de", "Quelle est la préposition après", "Verbe transitif ou intransitif ?",
  "Comment je conjugue ça au passé composé :", "Au futur simple, ça donne quoi", "Au subjonctif, on dit",
  "Y a-t-il une exception pour", "Est-ce que ce mot est un néologisme ?", "C'est tombé à l'examen :",
  "Question de grammaire sur", "Doute existentiel :",
  "Comment expliquer à un étranger ce qu'est", "Y a-t-il un équivalent en anglais pour",
  "J'adore la sonorité de ce mot", "Mon mot français préféré est", "Je déteste la sonorité de",
  "Mot difficile à prononcer :", "Virelangue avec le mot", "Rime parfaite pour",
  "Qu'est-ce qui rime avec", "Petit poème utilisant", "Paroles de chanson avec",
  "J'ai vu cet argot sur Twitter", "Les jeunes utilisent beaucoup :", "Le terme a fait le buzz sur TikTok",
  "Sujet tendance du jour :", "Que veut dire le hashtag", "Mème du jour avec",
  "C'est un truc de vieux ?", "Expression de boomer :", "Langage de la génération Z :",
  "Comment les gamers utilisent", "Terme technique en informatique :", "Dans le jargon des entreprises, qu'est-ce que",
  "Comment mettre ça sur un CV :", "Bon mot à utiliser au travail :", "E-mail formel utilisant",
  "Ça faisait bizarre quand j'ai dit", "J'ai fait une gaffe en utilisant", "On m'a corrigé pour avoir dit",
  "Je ne sais pas si ça s'écrit en un mot ou deux :", "Y a-t-il un trait d'union dans", "Est-ce que c'est masculin ou féminin :",
  "Ça prend un S ou un X au pluriel :", "Faut-il faire la liaison avec", "Double consonne dans",
  "Lettre muette dans", "Quel est le diminutif de",
  "Quel est l'augmentatif de", "Notion de base sur", "À quoi sert le mot",
  "Recherche rapide sur Google", "Recherche approfondie sur", "Chat GPT m'a suggéré le mot",
  "L'intelligence artificielle a généré :", "Je construis une phrase avec", "J'ai besoin d'inspiration pour utiliser",
  "Rédiger un texte avec", "Réécris la phrase en utilisant", "Dissertation parfaite utilisant",
  "Astuce de français :", "Moyen mnémotechnique pour retenir", "Association mentale pour le mot",
  "Carte mémoire d'aujourd'hui :", "Révision de vocabulaire :", "Test de niveau DELF/DALF :",
  "De quel niveau est ce mot (A1-C2) ?", "Mot courant dans les textes académiques :", "Jargon juridique :",
  "C'est du jargon médical ?", "Vocabulaire économique :", "Terme de philosophie :",
  "En sociologie, que signifie", "Concept psychologique de", "Explique-moi comme si j'avais 5 ans :",
  "Résumé rapide de", "Définition complète de", "Ce que Wikipédia dit sur",
  "Discuter de", "Échanger des idées sur", "Réflexion du jour avec le mot",
  "Ça me fait penser à", "J'associe ce mot à", "La première chose qui me vient à l'esprit avec",
  "Mot qui définit mon humeur aujourd'hui :", "État d'esprit :", "Ça décrit parfaitement",
  "Quand j'entends ça, j'imagine", "Une image qui représente", "Quelle couleur correspond au mot",
  "Y a-t-il une chanson sur", "Livre dont le titre contient", "Nom de film avec",
  "Personne célèbre qui dit toujours", "Phrase culte impliquant", "Slogan avec le mot",
  "Citation motivante avec", "Proverbe utilisant", "Dicton populaire avec",
  "Sagesse populaire sur", "Mythe ou réalité sur le mot", "La polémique autour de",
  "Pourquoi tout le monde parle de", "L'engouement pour le mot", "Ce mot a-t-il été annulé ?",
  "Appropriation culturelle du terme", "Sens originel de", "Comment le sens a évolué avec le temps :",
  "Évolution du mot", "Mot de l'année dernière :", "Pronostics pour le mot de l'année :",
  "Pour finir en beauté, utilise", "C'est du verlan ?", "Expression québécoise :",
  "En Belgique, on dit ça ?", "Mot typiquement suisse :", "L'Académie française accepte-t-elle le mot",

  // IT
  "Ho trovato questa parola:", "Come applicare la parola", "In quale contesto uso", "Gergo o formale:", 
  "Da dove è nato", "Cercando", "Esempi pratici di", "La grammatica di", "Dubbio su", 
  "Qualcuno sa cos'è", "L'origine segreta di", "Perché usare", "Non ho capito il termine", 
  "Come scrivere", "Contesto storico di", "Spiegazione rapida per", "Il concetto di", "Definisci", 
  "Cosa intende la gente per", "Parola del giorno:", "Cercando:", "Come coniugare", 
  "Qual è l'etimologia di", "La traduzione letterale di", "L'uso corretto di", 
  "Come non sbagliare a dire", "Puoi spiegare", "Che aria tira con", "Cosa significa in gergo", 
  "Nella vita di tutti i giorni, come uso", "Prendendo appunti su:", "Memorizzare la parola", 
  "Cosa dice il dizionario su", "Qual è il punto di", "Testando la parola", 
  "Scommetto che non sai cos'è", "Leggendo di", "Curiosità su", "Dimmi di più su", 
  "Il sinonimo perfetto per", "Antonimo esatto di", "Citazione con la parola", "Frase di esempio con", 
  "Come pronunciare correttamente", "La pronuncia esatta di",
  "Si usa più nel parlato o nello scritto", "Che tono ha questa parola", 
  "Ci sono modi di dire con la parola", "È una parola di uso quotidiano", 
  "Qual è la differenza tra", "Come usare questo in una frase", 
  "Esiste un gergo per", "Qual è la sillaba tonica di", "Quale preposizione si usa con", 
  "Si tratta di un falso amico",
  "Qual è il significato di", "Volevo saperne di più su", "Qualcuno mi spiega cos'è",
  "Oggi ho imparato il termine", "Ho sempre avuto un dubbio su", "Come traduco",
  "Cosa diamine significa", "Non ho mai sentito la parola", "Da dove hanno tirato fuori l'espressione",
  "Sto cercando di capire", "Mi sono imbattuto nella parola", "Come applicarlo nella vita di tutti i giorni:",
  "È una parolaccia?", "Qual è l'antonimo di", "Sinonimi interessanti per",
  "C'è uno slang per", "Come dirlo in modo formale", "Ho trovato questa espressione in un libro:",
  "Oggi studio:", "Cosa dice Google su", "Qual è la categoria grammaticale di",
  "È un sostantivo o un aggettivo?", "Qual è il plurale di", "Questa parola ha l'accento?",
  "Regole d'uso per", "Qual è la radice della parola", "Suffisso e prefisso di",
  "Si può usare in senso figurato?", "Il senso letterale di", "Come inserire questo in un testo:",
  "Il professore oggi ha menzionato:", "Ho visto in un film la parola", "È apparso in una serie tv:",
  "Come si pronuncia questo:", "Qual è l'origine storica di", "Chi ha inventato la parola",
  "Viene dal latino o dal greco?", "Parola molto usata in Italia:", "Al nord e al sud significa la stessa cosa?",
  "È un'espressione dialettale?", "Espressione tipica di", "L'Accademia della Crusca accetta questa parola?",
  "Il correttore ortografico ha segnato:", "Parola elegante per fare colpo:", "Vocabolario avanzato:",
  "Arricchendo il mio vocabolario con", "Sostituisci la parola", "Un altro modo per dire",
  "Modo educato per dire", "Bella parola del giorno:", "Che parola strana:",
  "La pronuncia mi confonde in", "Ho scritto bene la parola", "Qual è la desinenza di",
  "Analisi logica di", "Quale preposizione regge", "Verbo transitivo o intransitivo?",
  "Come coniugo questo al passato remoto:", "Al futuro semplice, come diventa", "Al congiuntivo si dice",
  "C'è qualche eccezione per", "Questa parola è un neologismo?", "È uscito all'esame:",
  "Domanda di grammatica su", "Dubbio amletico:",
  "Come spiegare a uno straniero cos'è", "C'è un equivalente in inglese per",
  "Adoro il suono di questa parola", "La mia parola italiana preferita è", "Odio come suona",
  "Parola difficile da pronunciare:", "Scioglilingua con la parola", "Rima perfetta per",
  "Cosa fa rima con", "Breve poesia usando", "Testo di una canzone con",
  "Ho visto questo slang su Twitter", "I giovani usano molto:", "Il termine è diventato virale su TikTok",
  "Argomento in tendenza oggi:", "Cosa significa l'hashtag", "Meme del giorno con",
  "È una cosa da vecchi?", "Espressione da boomer:", "Linguaggio della generazione Z:",
  "Come lo usano i gamer", "Termine tecnico di informatica:", "Nel gergo aziendale, cos'è",
  "Come metterlo nel curriculum:", "Buona parola da usare a lavoro:", "Email formale usando",
  "Suonava strano quando ho detto", "Ho fatto una gaffe usando", "Mi hanno corretto per aver detto",
  "Non so se si scrive attaccato o staccato:", "Ci vuole l'apostrofo in", "È maschile o femminile:",
  "Al plurale finisce in I o in E:", "Ci vuole la doppia in", "C'è la lettera muta H in",
  "Qual è il diminutivo di", "Qual è l'accrescitivo di", "Vezzeggiativo o dispregiativo di",
  "Nozione di base su", "A cosa serve la parola",
  "Ricerca rapida su Google", "Ricerca approfondita su", "Chat GPT mi ha suggerito la parola",
  "L'intelligenza artificiale ha generato:", "Sto costruendo una frase con", "Ho bisogno di ispirazione per usare",
  "Scrivere un testo con", "Riscrivi la frase usando", "Tema perfetto usando",
  "Trucco di italiano:", "Metodo mnemonico per ricordare", "Associazione mentale per la parola",
  "Flashcard di oggi:", "Ripasso del vocabolario:", "Test di livello CILS/CELI:",
  "Che livello è questa parola (A1-C2)?", "Parola comune nei testi accademici:", "Gergo giuridico:",
  "È gergo medico?", "Vocabolario di economia:", "Termine di filosofia:",
  "In sociologia, cosa significa", "Concetto psicologico di", "Spiegalo come se avessi 5 anni:",
  "Riassunto rapido di", "Definizione lunga di", "Cosa dice Wikipedia su",
  "Chiacchierando di", "Scambiando idee su", "Riflessione del giorno con la parola",
  "Questo mi fa pensare a", "Associo questa parola a", "La prima cosa che mi viene in mente con",
  "Parola che definisce il mio umore oggi:", "Stato d'animo:", "Questo descrive perfettamente",
  "Quando sento questo, immagino", "Un'immagine che rappresenta", "Quale colore si abbina alla parola",
  "C'è qualche canzone su", "Libro che ha nel titolo", "Nome di un film con",
  "Persona famosa che dice sempre", "Frase celebre che coinvolge", "Slogan con la parola",
  "Frase motivazionale con", "Proverbio che usa", "Modo di dire con",
  "Saggezza popolare su", "Mito o verità sulla parola", "La polemica intorno a",
  "Perché tutti parlano di", "Il clamore per la parola", "Questa parola è stata cancellata?",
  "Appropriazione culturale del termine", "Significato originale di", "Come è cambiato il senso col tempo:",
  "Evoluzione della parola", "Parola dell'anno scorso:", "Scommesse per la parola dell'anno:",
  "Per chiudere in bellezza, usa", "È un termine romano?", "Espressione tipica milanese:",
  "Nel dialetto napoletano significa:", "Si dice anche al sud?", "Questo è un falso alterato?",
  "Preposizione articolata corretta per",

  // etc
  "Google:", "Bing:", "DuckDuckGo:", "Brave:", "Yahoo:", "Search:", "Query:", 
  "Find:", "API:", "GET:", "POST:", "JSON:", "Payload:", "Fetch:", 
  "Response:", "Request:", "Body:", "Log:", "Console:", "Input:", 
  "Output:", "Result:", "Return:", "Status:", "200 OK:", "404:", 
  "Data:", "Cache:", "DB:", "Sys:", "App:", "Web:", "Bot:", "AI:", 
  "GPT:", "Gemini:", "Prompt:", "LLM:", "Model:", "String:", "Text:", 
  "Var:", "Run:", "Exec:", "Cmd:", "Terminal:", "Ping:", "Host:", 
  "User:", "System:", "Node:", "Script:", "Code:", "Regex:", "Parse:", 
  "Header:", "Token:", "Auth:", "Index:", "Tag:", "Label:", "Value:", 
  "Key:", "Item:", "Word:", "Term:", "Info:", "Msg:", "Alert:", 
  "Hook:", "Action:", "Event:", "Task:", "Job:", "Process:",
  "URL:", "URI:", "HTTP:", "HTTPS:", "FTP:", "SSH:", "TLS:", "SSL:", "TCP:", "UDP:", 
  "IP:", "DNS:", "VPN:", "LAN:", "WAN:", "MAC:", "Port:", "Socket:", "Host:", "Localhost:", 
  "IPv4:", "IPv6:", "Router:", "Proxy:", "Gateway:", "Ping:", "Trace:", "CORS:", "REST:", 
  "SOAP:", "GraphQL:", "Webhook:", "DOM:", "CSS:", "HTML:", "XML:", "YAML:", "CSV:", 
  "JS:", "C#:", "Node:", "NPM:", "Env:", "Config:", "Path:", "Dir:", "File:", "Read:", 
  "Write:", "Stream:", "Buffer:", "Byte:", "Bit:", "Hash:", "Crypt:", "Salt:", "Session:", 
  "Cookie:", "JWT:", "OAuth:", "Auth:", "Login:", "Logout:", "Admin:", "User:", "Role:", 
  "Perm:", "Grant:", "Deny:", "Allow:", "Block:", "Ban:", "Kick:", "Mute:", "BIOS:", 
  "CPU:", "GPU:", "RAM:", "VRAM:", "SSD:", "HDD:", "Disk:", "Boot:", "Root:", "Kernel:", 
  "Shell:", "Bash:", "CLI:", "GUI:", "OS:", "VM:", "Docker:", "Pod:", "NodeJS:", "Git:", 
  "Repo:", "Commit:", "Push:", "Pull:", "Merge:", "Branch:", "Tag:", "Release:", "Build:", 
  "Deploy:", "Dev:", "Prod:", "Stage:", "Test:", "QA:", "Bug:", "Fix:", "Patch:", "Issue:", 
  "Ticket:", "Log:", "Err:", "Warn:", "Debug:", "Fatal:", "Crash:", "Dump:", "Memory:", 
  "Load:", "Temp:", "Fan:", "Clock:", "Thread:", "Core:", "Sync:", "Async:", "Await:", 
  "Promise:", "Callback:", "Event:", "Listener:", "Trigger:", "State:", "Props:", "Store:", 
  "View:", "Ctrl:", "Model:", "Class:", "Object:", "Struct:", "Enum:", "Type:", "Var:", 
  "Let:", "Const:", "Func:", "Method:", "Loop:", "Timer:", "Timeout:", "Interval:", 
  "TimeAttack:", "Menu:", "Lang:", "I18n:", "Locale:", "Game:", "Score:", "Level:", "XP:", 
  "UI:", "UX:", "Render:", "Pixel:", "FPS:", "Lat:", "Lon:", "Geo:", "Map:", "App:", 
  "Pkg:", "Mod:", "Lib:", "Bin:", "Src:", "Dist:", "Out:", "In:", "Cmd:", "Arg:", 
  "Param:", "Query:", "Body:", "Header:", "Footer:", "Nav:", "Main:", "Aside:", "Sect:", 
  "Div:", "Span:", "Icon:", "Img:", "Vid:", "Media:", "Blob:", "Doc:", "DB:", "SQL:", 
  "NoSQL:", "Table:", "Row:", "Col:", "Field:", "Index:", "Key:", "Val:", "Data:", "Meta:", 
  "Cache:", "Redis:", "Mongo:", "ORM:", "Record:", "Entry:", "Item:", "List:", "Array:", 
  "Set:", "Dict:", "Tuple:", "Graph:", "Tree:", "Edge:", "Vertex:"

];

const caracteres = [/*
    "@version": "16.0.0",
    "@author": "Chalda Pnuzig <chalda_emoji＠chalda.it>",
    "@copyright": "Chalda Pnuzig 2021-2024",
    "@see": "{@link https://github.com/chalda-pnuzig/emojis.json|GitHub}",
    "@license": "ISC",
*/
    "😀",
    "😃",
    "😄",
    "😁",
    "😆",
    "😅",
    "🤣",
    "😂",
    "🙂",
    "🙃",
    "🫠",
    "😉",
    "😊",
    "😇",
    "🥰",
    "😍",
    "🤩",
    "😘",
    "😗",
    "☺",
    "😚",
    "😙",
    "🥲",
    "😋",
    "😛",
    "😜",
    "🤪",
    "😝",
    "🤑",
    "🤗",
    "🤭",
    "🫢",
    "🫣",
    "🤫",
    "🤔",
    "🫡",
    "🤐",
    "🤨",
    "😐",
    "😑",
    "😶",
    "🫥",
    "😶‍🌫️",
    "😏",
    "😒",
    "🙄",
    "😬",
    "😮‍💨",
    "🤥",
    "🫨",
    "🙂‍↔️",
    "🙂‍↕️",
    "😌",
    "😔",
    "😪",
    "🤤",
    "😴",
    "🫩",
    "😷",
    "🤒",
    "🤕",
    "🤢",
    "🤮",
    "🤧",
    "🥵",
    "🥶",
    "🥴",
    "😵",
    "😵‍💫",
    "🤯",
    "🤠",
    "🥳",
    "🥸",
    "😎",
    "🤓",
    "🧐",
    "😕",
    "🫤",
    "😟",
    "🙁",
    "☹",
    "😮",
    "😯",
    "😲",
    "😳",
    "🥺",
    "🥹",
    "😦",
    "😧",
    "😨",
    "😰",
    "😥",
    "😢",
    "😭",
    "😱",
    "😖",
    "😣",
    "😞",
    "😓",
    "😩",
    "😫",
    "🥱",
    "😤",
    "😡",
    "😠",
    "🤬",
    "😈",
    "👿",
    "💀",
    "☠",
    "💩",
    "🤡",
    "👹",
    "👺",
    "👻",
    "👽",
    "👾",
    "🤖",
    "😺",
    "😸",
    "😹",
    "😻",
    "😼",
    "😽",
    "🙀",
    "😿",
    "😾",
    "🙈",
    "🙉",
    "🙊",
    "💌",
    "💘",
    "💝",
    "💖",
    "💗",
    "💓",
    "💞",
    "💕",
    "💟",
    "❣",
    "💔",
    "❤️‍🔥",
    "❤️‍🩹",
    "❤",
    "🩷",
    "🧡",
    "💛",
    "💚",
    "💙",
    "🩵",
    "💜",
    "🤎",
    "🖤",
    "🩶",
    "🤍",
    "💋",
    "💯",
    "💢",
    "💥",
    "💫",
    "💦",
    "💨",
    "🕳",
    "💬",
    "👁️‍🗨️",
    "🗨",
    "🗯",
    "💭",
    "💤",
    "👋",
    "🤚",
    "🖐",
    "✋",
    "🖖",
    "🫱",
    "🫲",
    "🫳",
    "🫴",
    "🫷",
    "🫸",
    "👌",
    "🤌",
    "🤏",
    "✌",
    "🤞",
    "🫰",
    "🤟",
    "🤘",
    "🤙",
    "👈",
    "👉",
    "👆",
    "🖕",
    "👇",
    "☝",
    "🫵",
    "👍",
    "👎",
    "✊",
    "👊",
    "🤛",
    "🤜",
    "👏",
    "🙌",
    "🫶",
    "👐",
    "🤲",
    "🤝",
    "🙏",
    "✍",
    "💅",
    "🤳",
    "💪",
    "🦾",
    "🦿",
    "🦵",
    "🦶",
    "👂",
    "🦻",
    "👃",
    "🧠",
    "🫀",
    "🫁",
    "🦷",
    "🦴",
    "👀",
    "👁",
    "👅",
    "👄",
    "🫦",
    "👶",
    "🧒",
    "👦",
    "👧",
    "🧑",
    "👱",
    "👨",
    "🧔",
    "🧔‍♂️",
    "🧔‍♀️",
    "👨‍🦰",
    "👨‍🦱",
    "👨‍🦳",
    "👨‍🦲",
    "👩",
    "👩‍🦰",
    "🧑‍🦰",
    "👩‍🦱",
    "🧑‍🦱",
    "👩‍🦳",
    "🧑‍🦳",
    "👩‍🦲",
    "🧑‍🦲",
    "👱‍♀️",
    "👱‍♂️",
    "🧓",
    "👴",
    "👵",
    "🙍",
    "🙍‍♂️",
    "🙍‍♀️",
    "🙎",
    "🙎‍♂️",
    "🙎‍♀️",
    "🙅",
    "🙅‍♂️",
    "🙅‍♀️",
    "🙆",
    "🙆‍♂️",
    "🙆‍♀️",
    "💁",
    "💁‍♂️",
    "💁‍♀️",
    "🙋",
    "🙋‍♂️",
    "🙋‍♀️",
    "🧏",
    "🧏‍♂️",
    "🧏‍♀️",
    "🙇",
    "🙇‍♂️",
    "🙇‍♀️",
    "🤦",
    "🤦‍♂️",
    "🤦‍♀️",
    "🤷",
    "🤷‍♂️",
    "🤷‍♀️",
    "🧑‍⚕️",
    "👨‍⚕️",
    "👩‍⚕️",
    "🧑‍🎓",
    "👨‍🎓",
    "👩‍🎓",
    "🧑‍🏫",
    "👨‍🏫",
    "👩‍🏫",
    "🧑‍⚖️",
    "👨‍⚖️",
    "👩‍⚖️",
    "🧑‍🌾",
    "👨‍🌾",
    "👩‍🌾",
    "🧑‍🍳",
    "👨‍🍳",
    "👩‍🍳",
    "🧑‍🔧",
    "👨‍🔧",
    "👩‍🔧",
    "🧑‍🏭",
    "👨‍🏭",
    "👩‍🏭",
    "🧑‍💼",
    "👨‍💼",
    "👩‍💼",
    "🧑‍🔬",
    "👨‍🔬",
    "👩‍🔬",
    "🧑‍💻",
    "👨‍💻",
    "👩‍💻",
    "🧑‍🎤",
    "👨‍🎤",
    "👩‍🎤",
    "🧑‍🎨",
    "👨‍🎨",
    "👩‍🎨",
    "🧑‍✈️",
    "👨‍✈️",
    "👩‍✈️",
    "🧑‍🚀",
    "👨‍🚀",
    "👩‍🚀",
    "🧑‍🚒",
    "👨‍🚒",
    "👩‍🚒",
    "👮",
    "👮‍♂️",
    "👮‍♀️",
    "🕵",
    "🕵️‍♂️",
    "🕵️‍♀️",
    "💂",
    "💂‍♂️",
    "💂‍♀️",
    "🥷",
    "👷",
    "👷‍♂️",
    "👷‍♀️",
    "🫅",
    "🤴",
    "👸",
    "👳",
    "👳‍♂️",
    "👳‍♀️",
    "👲",
    "🧕",
    "🤵",
    "🤵‍♂️",
    "🤵‍♀️",
    "👰",
    "👰‍♂️",
    "👰‍♀️",
    "🤰",
    "🫃",
    "🫄",
    "🤱",
    "👩‍🍼",
    "👨‍🍼",
    "🧑‍🍼",
    "👼",
    "🎅",
    "🤶",
    "🧑‍🎄",
    "🦸",
    "🦸‍♂️",
    "🦸‍♀️",
    "🦹",
    "🦹‍♂️",
    "🦹‍♀️",
    "🧙",
    "🧙‍♂️",
    "🧙‍♀️",
    "🧚",
    "🧚‍♂️",
    "🧚‍♀️",
    "🧛",
    "🧛‍♂️",
    "🧛‍♀️",
    "🧜",
    "🧜‍♂️",
    "🧜‍♀️",
    "🧝",
    "🧝‍♂️",
    "🧝‍♀️",
    "🧞",
    "🧞‍♂️",
    "🧞‍♀️",
    "🧟",
    "🧟‍♂️",
    "🧟‍♀️",
    "🧌",
    "💆",
    "💆‍♂️",
    "💆‍♀️",
    "💇",
    "💇‍♂️",
    "💇‍♀️",
    "🚶",
    "🚶‍♂️",
    "🚶‍♀️",
    "🚶‍➡️",
    "🚶‍♀️‍➡️",
    "🚶‍♂️‍➡️",
    "🧍",
    "🧍‍♂️",
    "🧍‍♀️",
    "🧎",
    "🧎‍♂️",
    "🧎‍♀️",
    "🧎‍➡️",
    "🧎‍♀️‍➡️",
    "🧎‍♂️‍➡️",
    "🧑‍🦯",
    "🧑‍🦯‍➡️",
    "👨‍🦯",
    "👨‍🦯‍➡️",
    "👩‍🦯",
    "👩‍🦯‍➡️",
    "🧑‍🦼",
    "🧑‍🦼‍➡️",
    "👨‍🦼",
    "👨‍🦼‍➡️",
    "👩‍🦼",
    "👩‍🦼‍➡️",
    "🧑‍🦽",
    "🧑‍🦽‍➡️",
    "👨‍🦽",
    "👨‍🦽‍➡️",
    "👩‍🦽",
    "👩‍🦽‍➡️",
    "🏃",
    "🏃‍♂️",
    "🏃‍♀️",
    "🏃‍➡️",
    "🏃‍♀️‍➡️",
    "🏃‍♂️‍➡️",
    "💃",
    "🕺",
    "🕴",
    "👯",
    "👯‍♂️",
    "👯‍♀️",
    "🧖",
    "🧖‍♂️",
    "🧖‍♀️",
    "🧗",
    "🧗‍♂️",
    "🧗‍♀️",
    "🤺",
    "🏇",
    "⛷",
    "🏂",
    "🏌",
    "🏌️‍♂️",
    "🏌️‍♀️",
    "🏄",
    "🏄‍♂️",
    "🏄‍♀️",
    "🚣",
    "🚣‍♂️",
    "🚣‍♀️",
    "🏊",
    "🏊‍♂️",
    "🏊‍♀️",
    "⛹",
    "⛹️‍♂️",
    "⛹️‍♀️",
    "🏋",
    "🏋️‍♂️",
    "🏋️‍♀️",
    "🚴",
    "🚴‍♂️",
    "🚴‍♀️",
    "🚵",
    "🚵‍♂️",
    "🚵‍♀️",
    "🤸",
    "🤸‍♂️",
    "🤸‍♀️",
    "🤼",
    "🤼‍♂️",
    "🤼‍♀️",
    "🤽",
    "🤽‍♂️",
    "🤽‍♀️",
    "🤾",
    "🤾‍♂️",
    "🤾‍♀️",
    "🤹",
    "🤹‍♂️",
    "🤹‍♀️",
    "🧘",
    "🧘‍♂️",
    "🧘‍♀️",
    "🛀",
    "🛌",
    "🧑‍🤝‍🧑",
    "👭",
    "👫",
    "👬",
    "💏",
    "👩‍❤️‍💋‍👨",
    "👨‍❤️‍💋‍👨",
    "👩‍❤️‍💋‍👩",
    "💑",
    "👩‍❤️‍👨",
    "👨‍❤️‍👨",
    "👩‍❤️‍👩",
    "👨‍👩‍👦",
    "👨‍👩‍👧",
    "👨‍👩‍👧‍👦",
    "👨‍👩‍👦‍👦",
    "👨‍👩‍👧‍👧",
    "👨‍👨‍👦",
    "👨‍👨‍👧",
    "👨‍👨‍👧‍👦",
    "👨‍👨‍👦‍👦",
    "👨‍👨‍👧‍👧",
    "👩‍👩‍👦",
    "👩‍👩‍👧",
    "👩‍👩‍👧‍👦",
    "👩‍👩‍👦‍👦",
    "👩‍👩‍👧‍👧",
    "👨‍👦",
    "👨‍👦‍👦",
    "👨‍👧",
    "👨‍👧‍👦",
    "👨‍👧‍👧",
    "👩‍👦",
    "👩‍👦‍👦",
    "👩‍👧",
    "👩‍👧‍👦",
    "👩‍👧‍👧",
    "🗣",
    "👤",
    "👥",
    "🫂",
    "👪",
    "🧑‍🧑‍🧒",
    "🧑‍🧑‍🧒‍🧒",
    "🧑‍🧒",
    "🧑‍🧒‍🧒",
    "👣",
    "🫆",
    "🦰",
    "🦱",
    "🦳",
    "🦲",
    "🐵",
    "🐒",
    "🦍",
    "🦧",
    "🐶",
    "🐕",
    "🦮",
    "🐕‍🦺",
    "🐩",
    "🐺",
    "🦊",
    "🦝",
    "🐱",
    "🐈",
    "🐈‍⬛",
    "🦁",
    "🐯",
    "🐅",
    "🐆",
    "🐴",
    "🫎",
    "🫏",
    "🐎",
    "🦄",
    "🦓",
    "🦌",
    "🦬",
    "🐮",
    "🐂",
    "🐃",
    "🐄",
    "🐷",
    "🐖",
    "🐗",
    "🐽",
    "🐏",
    "🐑",
    "🐐",
    "🐪",
    "🐫",
    "🦙",
    "🦒",
    "🐘",
    "🦣",
    "🦏",
    "🦛",
    "🐭",
    "🐁",
    "🐀",
    "🐹",
    "🐰",
    "🐇",
    "🐿",
    "🦫",
    "🦔",
    "🦇",
    "🐻",
    "🐻‍❄️",
    "🐨",
    "🐼",
    "🦥",
    "🦦",
    "🦨",
    "🦘",
    "🦡",
    "🐾",
    "🦃",
    "🐔",
    "🐓",
    "🐣",
    "🐤",
    "🐥",
    "🐦",
    "🐧",
    "🕊",
    "🦅",
    "🦆",
    "🦢",
    "🦉",
    "🦤",
    "🪶",
    "🦩",
    "🦚",
    "🦜",
    "🪽",
    "🐦‍⬛",
    "🪿",
    "🐦‍🔥",
    "🐸",
    "🐊",
    "🐢",
    "🦎",
    "🐍",
    "🐲",
    "🐉",
    "🦕",
    "🦖",
    "🐳",
    "🐋",
    "🐬",
    "🦭",
    "🐟",
    "🐠",
    "🐡",
    "🦈",
    "🐙",
    "🐚",
    "🪸",
    "🪼",
    "🦀",
    "🦞",
    "🦐",
    "🦑",
    "🦪",
    "🐌",
    "🦋",
    "🐛",
    "🐜",
    "🐝",
    "🪲",
    "🐞",
    "🦗",
    "🪳",
    "🕷",
    "🕸",
    "🦂",
    "🦟",
    "🪰",
    "🪱",
    "🦠",
    "💐",
    "🌸",
    "💮",
    "🪷",
    "🏵",
    "🌹",
    "🥀",
    "🌺",
    "🌻",
    "🌼",
    "🌷",
    "🪻",
    "🌱",
    "🪴",
    "🌲",
    "🌳",
    "🌴",
    "🌵",
    "🌾",
    "🌿",
    "☘",
    "🍀",
    "🍁",
    "🍂",
    "🍃",
    "🪹",
    "🪺",
    "🍄",
    "🪾",
    "🍇",
    "🍈",
    "🍉",
    "🍊",
    "🍋",
    "🍋‍🟩",
    "🍌",
    "🍍",
    "🥭",
    "🍎",
    "🍏",
    "🍐",
    "🍑",
    "🍒",
    "🍓",
    "🫐",
    "🥝",
    "🍅",
    "🫒",
    "🥥",
    "🥑",
    "🍆",
    "🥔",
    "🥕",
    "🌽",
    "🌶",
    "🫑",
    "🥒",
    "🥬",
    "🥦",
    "🧄",
    "🧅",
    "🥜",
    "🫘",
    "🌰",
    "🫚",
    "🫛",
    "🍄‍🟫",
    "🫜",
    "🍞",
    "🥐",
    "🥖",
    "🫓",
    "🥨",
    "🥯",
    "🥞",
    "🧇",
    "🧀",
    "🍖",
    "🍗",
    "🥩",
    "🥓",
    "🍔",
    "🍟",
    "🍕",
    "🌭",
    "🥪",
    "🌮",
    "🌯",
    "🫔",
    "🥙",
    "🧆",
    "🥚",
    "🍳",
    "🥘",
    "🍲",
    "🫕",
    "🥣",
    "🥗",
    "🍿",
    "🧈",
    "🧂",
    "🥫",
    "🍱",
    "🍘",
    "🍙",
    "🍚",
    "🍛",
    "🍜",
    "🍝",
    "🍠",
    "🍢",
    "🍣",
    "🍤",
    "🍥",
    "🥮",
    "🍡",
    "🥟",
    "🥠",
    "🥡",
    "🍦",
    "🍧",
    "🍨",
    "🍩",
    "🍪",
    "🎂",
    "🍰",
    "🧁",
    "🥧",
    "🍫",
    "🍬",
    "🍭",
    "🍮",
    "🍯",
    "🍼",
    "🥛",
    "☕",
    "🫖",
    "🍵",
    "🍶",
    "🍾",
    "🍷",
    "🍸",
    "🍹",
    "🍺",
    "🍻",
    "🥂",
    "🥃",
    "🫗",
    "🥤",
    "🧋",
    "🧃",
    "🧉",
    "🧊",
    "🥢",
    "🍽",
    "🍴",
    "🥄",
    "🔪",
    "🫙",
    "🏺",
    "🌍",
    "🌎",
    "🌏",
    "🌐",
    "🗺",
    "🗾",
    "🧭",
    "🏔",
    "⛰",
    "🌋",
    "🗻",
    "🏕",
    "🏖",
    "🏜",
    "🏝",
    "🏞",
    "🏟",
    "🏛",
    "🏗",
    "🧱",
    "🪨",
    "🪵",
    "🛖",
    "🏘",
    "🏚",
    "🏠",
    "🏡",
    "🏢",
    "🏣",
    "🏤",
    "🏥",
    "🏦",
    "🏨",
    "🏩",
    "🏪",
    "🏫",
    "🏬",
    "🏭",
    "🏯",
    "🏰",
    "💒",
    "🗼",
    "🗽",
    "⛪",
    "🕌",
    "🛕",
    "🕍",
    "⛩",
    "🕋",
    "⛲",
    "⛺",
    "🌁",
    "🌃",
    "🏙",
    "🌄",
    "🌅",
    "🌆",
    "🌇",
    "🌉",
    "♨",
    "🎠",
    "🛝",
    "🎡",
    "🎢",
    "💈",
    "🎪",
    "🚂",
    "🚃",
    "🚄",
    "🚅",
    "🚆",
    "🚇",
    "🚈",
    "🚉",
    "🚊",
    "🚝",
    "🚞",
    "🚋",
    "🚌",
    "🚍",
    "🚎",
    "🚐",
    "🚑",
    "🚒",
    "🚓",
    "🚔",
    "🚕",
    "🚖",
    "🚗",
    "🚘",
    "🚙",
    "🛻",
    "🚚",
    "🚛",
    "🚜",
    "🏎",
    "🏍",
    "🛵",
    "🦽",
    "🦼",
    "🛺",
    "🚲",
    "🛴",
    "🛹",
    "🛼",
    "🚏",
    "🛣",
    "🛤",
    "🛢",
    "⛽",
    "🛞",
    "🚨",
    "🚥",
    "🚦",
    "🛑",
    "🚧",
    "⚓",
    "🛟",
    "⛵",
    "🛶",
    "🚤",
    "🛳",
    "⛴",
    "🛥",
    "🚢",
    "✈",
    "🛩",
    "🛫",
    "🛬",
    "🪂",
    "💺",
    "🚁",
    "🚟",
    "🚠",
    "🚡",
    "🛰",
    "🚀",
    "🛸",
    "🛎",
    "🧳",
    "⌛",
    "⏳",
    "⌚",
    "⏰",
    "⏱",
    "⏲",
    "🕰",
    "🕛",
    "🕧",
    "🕐",
    "🕜",
    "🕑",
    "🕝",
    "🕒",
    "🕞",
    "🕓",
    "🕟",
    "🕔",
    "🕠",
    "🕕",
    "🕡",
    "🕖",
    "🕢",
    "🕗",
    "🕣",
    "🕘",
    "🕤",
    "🕙",
    "🕥",
    "🕚",
    "🕦",
    "🌑",
    "🌒",
    "🌓",
    "🌔",
    "🌕",
    "🌖",
    "🌗",
    "🌘",
    "🌙",
    "🌚",
    "🌛",
    "🌜",
    "🌡",
    "☀",
    "🌝",
    "🌞",
    "🪐",
    "⭐",
    "🌟",
    "🌠",
    "🌌",
    "☁",
    "⛅",
    "⛈",
    "🌤",
    "🌥",
    "🌦",
    "🌧",
    "🌨",
    "🌩",
    "🌪",
    "🌫",
    "🌬",
    "🌀",
    "🌈",
    "🌂",
    "☂",
    "☔",
    "⛱",
    "⚡",
    "❄",
    "☃",
    "⛄",
    "☄",
    "🔥",
    "💧",
    "🌊",
    "🎃",
    "🎄",
    "🎆",
    "🎇",
    "🧨",
    "✨",
    "🎈",
    "🎉",
    "🎊",
    "🎋",
    "🎍",
    "🎎",
    "🎏",
    "🎐",
    "🎑",
    "🧧",
    "🎀",
    "🎁",
    "🎗",
    "🎟",
    "🎫",
    "🎖",
    "🏆",
    "🏅",
    "🥇",
    "🥈",
    "🥉",
    "⚽",
    "⚾",
    "🥎",
    "🏀",
    "🏐",
    "🏈",
    "🏉",
    "🎾",
    "🥏",
    "🎳",
    "🏏",
    "🏑",
    "🏒",
    "🥍",
    "🏓",
    "🏸",
    "🥊",
    "🥋",
    "🥅",
    "⛳",
    "⛸",
    "🎣",
    "🤿",
    "🎽",
    "🎿",
    "🛷",
    "🥌",
    "🎯",
    "🪀",
    "🪁",
    "🔫",
    "🎱",
    "🔮",
    "🪄",
    "🎮",
    "🕹",
    "🎰",
    "🎲",
    "🧩",
    "🧸",
    "🪅",
    "🪩",
    "🪆",
    "♠",
    "♥",
    "♦",
    "♣",
    "♟",
    "🃏",
    "🀄",
    "🎴",
    "🎭",
    "🖼",
    "🎨",
    "🧵",
    "🪡",
    "🧶",
    "🪢",
    "👓",
    "🕶",
    "🥽",
    "🥼",
    "🦺",
    "👔",
    "👕",
    "👖",
    "🧣",
    "🧤",
    "🧥",
    "🧦",
    "👗",
    "👘",
    "🥻",
    "🩱",
    "🩲",
    "🩳",
    "👙",
    "👚",
    "🪭",
    "👛",
    "👜",
    "👝",
    "🛍",
    "🎒",
    "🩴",
    "👞",
    "👟",
    "🥾",
    "🥿",
    "👠",
    "👡",
    "🩰",
    "👢",
    "🪮",
    "👑",
    "👒",
    "🎩",
    "🎓",
    "🧢",
    "🪖",
    "⛑",
    "📿",
    "💄",
    "💍",
    "💎",
    "🔇",
    "🔈",
    "🔉",
    "🔊",
    "📢",
    "📣",
    "📯",
    "🔔",
    "🔕",
    "🎼",
    "🎵",
    "🎶",
    "🎙",
    "🎚",
    "🎛",
    "🎤",
    "🎧",
    "📻",
    "🎷",
    "🪗",
    "🎸",
    "🎹",
    "🎺",
    "🎻",
    "🪕",
    "🥁",
    "🪘",
    "🪇",
    "🪈",
    "🪉",
    "📱",
    "📲",
    "☎",
    "📞",
    "📟",
    "📠",
    "🔋",
    "🪫",
    "🔌",
    "💻",
    "🖥",
    "🖨",
    "⌨",
    "🖱",
    "🖲",
    "💽",
    "💾",
    "💿",
    "📀",
    "🧮",
    "🎥",
    "🎞",
    "📽",
    "🎬",
    "📺",
    "📷",
    "📸",
    "📹",
    "📼",
    "🔍",
    "🔎",
    "🕯",
    "💡",
    "🔦",
    "🏮",
    "🪔",
    "📔",
    "📕",
    "📖",
    "📗",
    "📘",
    "📙",
    "📚",
    "📓",
    "📒",
    "📃",
    "📜",
    "📄",
    "📰",
    "🗞",
    "📑",
    "🔖",
    "🏷",
    "💰",
    "🪙",
    "💴",
    "💵",
    "💶",
    "💷",
    "💸",
    "💳",
    "🧾",
    "💹",
    "✉",
    "📧",
    "📨",
    "📩",
    "📤",
    "📥",
    "📦",
    "📫",
    "📪",
    "📬",
    "📭",
    "📮",
    "🗳",
    "✏",
    "✒",
    "🖋",
    "🖊",
    "🖌",
    "🖍",
    "📝",
    "💼",
    "📁",
    "📂",
    "🗂",
    "📅",
    "📆",
    "🗒",
    "🗓",
    "📇",
    "📈",
    "📉",
    "📊",
    "📋",
    "📌",
    "📍",
    "📎",
    "🖇",
    "📏",
    "📐",
    "✂",
    "🗃",
    "🗄",
    "🗑",
    "🔒",
    "🔓",
    "🔏",
    "🔐",
    "🔑",
    "🗝",
    "🔨",
    "🪓",
    "⛏",
    "⚒",
    "🛠",
    "🗡",
    "⚔",
    "💣",
    "🪃",
    "🏹",
    "🛡",
    "🪚",
    "🔧",
    "🪛",
    "🔩",
    "⚙",
    "🗜",
    "⚖",
    "🦯",
    "🔗",
    "⛓️‍💥",
    "⛓",
    "🪝",
    "🧰",
    "🧲",
    "🪜",
    "🪏",
    "⚗",
    "🧪",
    "🧫",
    "🧬",
    "🔬",
    "🔭",
    "📡",
    "💉",
    "🩸",
    "💊",
    "🩹",
    "🩼",
    "🩺",
    "🩻",
    "🚪",
    "🛗",
    "🪞",
    "🪟",
    "🛏",
    "🛋",
    "🪑",
    "🚽",
    "🪠",
    "🚿",
    "🛁",
    "🪤",
    "🪒",
    "🧴",
    "🧷",
    "🧹",
    "🧺",
    "🧻",
    "🪣",
    "🧼",
    "🫧",
    "🪥",
    "🧽",
    "🧯",
    "🛒",
    "🚬",
    "⚰",
    "🪦",
    "⚱",
    "🧿",
    "🪬",
    "🗿",
    "🪧",
    "🪪",
    "🏧",
    "🚮",
    "🚰",
    "♿",
    "🚹",
    "🚺",
    "🚻",
    "🚼",
    "🚾",
    "🛂",
    "🛃",
    "🛄",
    "🛅",
    "⚠",
    "🚸",
    "⛔",
    "🚫",
    "🚳",
    "🚭",
    "🚯",
    "🚱",
    "🚷",
    "📵",
    "🔞",
    "☢",
    "☣",
    "⬆",
    "↗",
    "➡",
    "↘",
    "⬇",
    "↙",
    "⬅",
    "↖",
    "↕",
    "↔",
    "↩",
    "↪",
    "⤴",
    "⤵",
    "🔃",
    "🔄",
    "🔙",
    "🔚",
    "🔛",
    "🔜",
    "🔝",
    "🛐",
    "⚛",
    "🕉",
    "✡",
    "☸",
    "☯",
    "✝",
    "☦",
    "☪",
    "☮",
    "🕎",
    "🔯",
    "🪯",
    "♈",
    "♉",
    "♊",
    "♋",
    "♌",
    "♍",
    "♎",
    "♏",
    "♐",
    "♑",
    "♒",
    "♓",
    "⛎",
    "🔀",
    "🔁",
    "🔂",
    "▶",
    "⏩",
    "⏭",
    "⏯",
    "◀",
    "⏪",
    "⏮",
    "🔼",
    "⏫",
    "🔽",
    "⏬",
    "⏸",
    "⏹",
    "⏺",
    "⏏",
    "🎦",
    "🔅",
    "🔆",
    "📶",
    "🛜",
    "📳",
    "📴",
    "♀",
    "♂",
    "⚧",
    "✖",
    "➕",
    "➖",
    "➗",
    "🟰",
    "♾",
    "‼",
    "⁉",
    "❓",
    "❔",
    "❕",
    "❗",
    "〰",
    "💱",
    "💲",
    "⚕",
    "♻",
    "⚜",
    "🔱",
    "📛",
    "🔰",
    "⭕",
    "✅",
    "☑",
    "✔",
    "❌",
    "❎",
    "➰",
    "➿",
    "〽",
    "✳",
    "✴",
    "❇",
    "©",
    "®",
    "™",
    "🫟",
    "#️⃣",
    "*️⃣",
    "0️⃣",
    "1️⃣",
    "2️⃣",
    "3️⃣",
    "4️⃣",
    "5️⃣",
    "6️⃣",
    "7️⃣",
    "8️⃣",
    "9️⃣",
    "🔟",
    "🔠",
    "🔡",
    "🔢",
    "🔣",
    "🔤",
    "🅰",
    "🆎",
    "🅱",
    "🆑",
    "🆒",
    "🆓",
    "ℹ",
    "🆔",
    "Ⓜ",
    "🆕",
    "🆖",
    "🅾",
    "🆗",
    "🅿",
    "🆘",
    "🆙",
    "🆚",
    "🈁",
    "🈂",
    "🈷",
    "🈶",
    "🈯",
    "🉐",
    "🈹",
    "🈚",
    "🈲",
    "🉑",
    "🈸",
    "🈴",
    "🈳",
    "㊗",
    "㊙",
    "🈺",
    "🈵",
    "🔴",
    "🟠",
    "🟡",
    "🟢",
    "🔵",
    "🟣",
    "🟤",
    "⚫",
    "⚪",
    "🟥",
    "🟧",
    "🟨",
    "🟩",
    "🟦",
    "🟪",
    "🟫",
    "⬛",
    "⬜",
    "◼",
    "◻",
    "◾",
    "◽",
    "▪",
    "▫",
    "🔶",
    "🔷",
    "🔸",
    "🔹",
    "🔺",
    "🔻",
    "💠",
    "🔘",
    "🔳",
    "🔲",
    "🏁",
    "🚩",
    "🎌",
    "🏴",
    "🏳",
    "🏳️‍🌈",
    "🏳️‍⚧️",
    "🏴‍☠️",
    "🇦🇨",
    "🇦🇩",
    "🇦🇪",
    "🇦🇫",
    "🇦🇬",
    "🇦🇮",
    "🇦🇱",
    "🇦🇲",
    "🇦🇴",
    "🇦🇶",
    "🇦🇷",
    "🇦🇸",
    "🇦🇹",
    "🇦🇺",
    "🇦🇼",
    "🇦🇽",
    "🇦🇿",
    "🇧🇦",
    "🇧🇧",
    "🇧🇩",
    "🇧🇪",
    "🇧🇫",
    "🇧🇬",
    "🇧🇭",
    "🇧🇮",
    "🇧🇯",
    "🇧🇱",
    "🇧🇲",
    "🇧🇳",
    "🇧🇴",
    "🇧🇶",
    "🇧🇷",
    "🇧🇸",
    "🇧🇹",
    "🇧🇻",
    "🇧🇼",
    "🇧🇾",
    "🇧🇿",
    "🇨🇦",
    "🇨🇨",
    "🇨🇩",
    "🇨🇫",
    "🇨🇬",
    "🇨🇭",
    "🇨🇮",
    "🇨🇰",
    "🇨🇱",
    "🇨🇲",
    "🇨🇳",
    "🇨🇴",
    "🇨🇵",
    "🇨🇶",
    "🇨🇷",
    "🇨🇺",
    "🇨🇻",
    "🇨🇼",
    "🇨🇽",
    "🇨🇾",
    "🇨🇿",
    "🇩🇪",
    "🇩🇬",
    "🇩🇯",
    "🇩🇰",
    "🇩🇲",
    "🇩🇴",
    "🇩🇿",
    "🇪🇦",
    "🇪🇨",
    "🇪🇪",
    "🇪🇬",
    "🇪🇭",
    "🇪🇷",
    "🇪🇸",
    "🇪🇹",
    "🇪🇺",
    "🇫🇮",
    "🇫🇯",
    "🇫🇰",
    "🇫🇲",
    "🇫🇴",
    "🇫🇷",
    "🇬🇦",
    "🇬🇧",
    "🇬🇩",
    "🇬🇪",
    "🇬🇫",
    "🇬🇬",
    "🇬🇭",
    "🇬🇮",
    "🇬🇱",
    "🇬🇲",
    "🇬🇳",
    "🇬🇵",
    "🇬🇶",
    "🇬🇷",
    "🇬🇸",
    "🇬🇹",
    "🇬🇺",
    "🇬🇼",
    "🇬🇾",
    "🇭🇰",
    "🇭🇲",
    "🇭🇳",
    "🇭🇷",
    "🇭🇹",
    "🇭🇺",
    "🇮🇨",
    "🇮🇩",
    "🇮🇪",
    "🇮🇱",
    "🇮🇲",
    "🇮🇳",
    "🇮🇴",
    "🇮🇶",
    "🇮🇷",
    "🇮🇸",
    "🇮🇹",
    "🇯🇪",
    "🇯🇲",
    "🇯🇴",
    "🇯🇵",
    "🇰🇪",
    "🇰🇬",
    "🇰🇭",
    "🇰🇮",
    "🇰🇲",
    "🇰🇳",
    "🇰🇵",
    "🇰🇷",
    "🇰🇼",
    "🇰🇾",
    "🇰🇿",
    "🇱🇦",
    "🇱🇧",
    "🇱🇨",
    "🇱🇮",
    "🇱🇰",
    "🇱🇷",
    "🇱🇸",
    "🇱🇹",
    "🇱🇺",
    "🇱🇻",
    "🇱🇾",
    "🇲🇦",
    "🇲🇨",
    "🇲🇩",
    "🇲🇪",
    "🇲🇫",
    "🇲🇬",
    "🇲🇭",
    "🇲🇰",
    "🇲🇱",
    "🇲🇲",
    "🇲🇳",
    "🇲🇴",
    "🇲🇵",
    "🇲🇶",
    "🇲🇷",
    "🇲🇸",
    "🇲🇹",
    "🇲🇺",
    "🇲🇻",
    "🇲🇼",
    "🇲🇽",
    "🇲🇾",
    "🇲🇿",
    "🇳🇦",
    "🇳🇨",
    "🇳🇪",
    "🇳🇫",
    "🇳🇬",
    "🇳🇮",
    "🇳🇱",
    "🇳🇴",
    "🇳🇵",
    "🇳🇷",
    "🇳🇺",
    "🇳🇿",
    "🇴🇲",
    "🇵🇦",
    "🇵🇪",
    "🇵🇫",
    "🇵🇬",
    "🇵🇭",
    "🇵🇰",
    "🇵🇱",
    "🇵🇲",
    "🇵🇳",
    "🇵🇷",
    "🇵🇸",
    "🇵🇹",
    "🇵🇼",
    "🇵🇾",
    "🇶🇦",
    "🇷🇪",
    "🇷🇴",
    "🇷🇸",
    "🇷🇺",
    "🇷🇼",
    "🇸🇦",
    "🇸🇧",
    "🇸🇨",
    "🇸🇩",
    "🇸🇪",
    "🇸🇬",
    "🇸🇭",
    "🇸🇮",
    "🇸🇯",
    "🇸🇰",
    "🇸🇱",
    "🇸🇲",
    "🇸🇳",
    "🇸🇴",
    "🇸🇷",
    "🇸🇸",
    "🇸🇹",
    "🇸🇻",
    "🇸🇽",
    "🇸🇾",
    "🇸🇿",
    "🇹🇦",
    "🇹🇨",
    "🇹🇩",
    "🇹🇫",
    "🇹🇬",
    "🇹🇭",
    "🇹🇯",
    "🇹🇰",
    "🇹🇱",
    "🇹🇲",
    "🇹🇳",
    "🇹🇴",
    "🇹🇷",
    "🇹🇹",
    "🇹🇻",
    "🇹🇼",
    "🇹🇿",
    "🇺🇦",
    "🇺🇬",
    "🇺🇲",
    "🇺🇳",
    "🇺🇸",
    "🇺🇾",
    "🇺🇿",
    "🇻🇦",
    "🇻🇨",
    "🇻🇪",
    "🇻🇬",
    "🇻🇮",
    "🇻🇳",
    "🇻🇺",
    "🇼🇫",
    "🇼🇸",
    "🇽🇰",
    "🇾🇪",
    "🇾🇹",
    "🇿🇦",
    "🇿🇲",
    "🇿🇼",
    "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
    "🏴󠁧󠁢󠁷󠁬󠁳󠁿"
]